import InfoNoticeEssay from "../templates/InfoNoticeEssay"
import WorksCited from "../templates/WorksCited"

export default function Narrowlanes() {
    return (
        <>
            <InfoNoticeEssay />
            <h1 className="essaytitle">How can narrower lanes prevent pedestrian deaths and make transportation faster?</h1>
            <div className="essaycontent">
                <p>According the Centers for Disease Control and Prevention, nearly 8,000 pedestrians were killed in car accidents in 2021; approximately <i>one death every hour and six minutes</i>. This is over 2,000 more than the 5,472 pedestrians killed in 1994 (“Making America Walkable”). Simultaneously, as the Federal Highway Administration writes from personal anecdotes, cities are “becoming increasingly difficult for people to navigate on foot,” with numerous accounts that pedestrians are not safe and destinations are too far from home to reasonably travel. The feeling of being unsafe while walking or biking seems to be common. This presents an interesting challenge: <b>how should cities build streets and roads while simultaneously making transportation safer and more efficient?</b></p>
                <p>The first step to fixing these issues is understanding why pedestrians are getting killed, and many urban advocates have pointed to two major sources of the trouble. The first major source is the speed of the cars, as higher vehicle speeds increase the severity of the injury and the chances of getting hit (“Pedestrian Safety”). The Center for Disease Control and Prevention [CDC] notes that most pedestrians that were killed in 2021 died on “high-capacity urban roads” with speed limits ranging between 45 to 55 miles per hour [mph]. The second major source is heavier vehicles like sport utility vehicles [SUVs] and trucks, as their weight means that a heavier vehicle may not have the capability to sufficiently brake if they could potentially hit a pedestrian (“Pedestrian Safety”). The CDC also notes that the greater weight of SUVs and trucks also means that more impact will be put onto the pedestrian if struck, increasing the damage and chance of death.</p>
                <p>Large vehicles like SUVs and trucks are also bad for cities, as they make congestion worse because of their length, take up more parking space because of their width, and are heavier and thus more likely to wreck and rollover. Durand-Wood dutifully notes this, continuing to say that the increasing size of vehicles – especially SUVs and trucks – gives some safety at the expense of everyone else outside of the vehicles. The so-called “vehicle size arms race” to achieve the safest and biggest vehicle comes at a high cost: “for each fatal crash that occupants of large vehicles avoid, at least 4.3 additional fatal crashes involving others occur” (qtd. in Durand-Wood). While the solution to the large vehicle problem isn’t exactly clear other than regulation of their sales, there is a clear-cut solution to speeding that would force drivers, including those in SUVs and trucks, to slow down.</p>
                <p>In 1997, at the 67th annual meeting at the Institute of Transportation Engineers, James Daisa and John Peers presented a study linking a connection between the perceived width of a road and its ‘calming effect’ on vehicle speed. They found that on wide streets with little side-street parking, there was virtually no calming effect on speed, whereas narrow streets with low to high levels of parking experienced moderate to high calming on speed, respectively. In city planning, narrow streets are often discouraged due to service vehicles like firetrucks or garbage collection (Daisa and Peers). However, Daisa and Peers note that the benefits are still there for pedestrians and bikers, who are hit far less often and sustain much smaller injuries since lower speeds reduce stopping distance, with many streets – especially residential streets – aiming to reduce speeds and save lives.</p>
                <p>In addition to this 1997 study, a 2023 report from the Johns Hopkins Bloomberg School of Public Health led by principal investigator Shima Hamidi analyzed over 1,100 street sections. This report shows that for speeds around 25 mph or lower, the speed is too slow for drivers to adjust their driving according to the lane width and risk crashing. However, speed classes from 30 mph and onward saw significantly more crashes when lanes are wider than nine feet across (Hamidi et al.). Hamidi et al. notes that while 9-foot lanes are beneficial, they may not be the most practical for all transportation, as many wider vehicles like oversized trucks use the same roads as personal vehicles. The authors also note that narrowing the lanes also isn’t the only solution, as the underlying issue is the perception of the width, so alternative methods like adding street fixtures or large trees would assist in slow speeds. This analysis demonstrated that the greatest determinant in car wrecks and pedestrian deaths is not the posted speed limit, but rather how comfortable drivers feel in their lanes at their speed, which wider lanes only amplify. Therefore, while one could assume that the solution to illegal speeding is to raise the speed limit, the actual solution is to alter the infrastructure to force drivers to pay closer attention to their environment and go slower (Hamidi et al.).</p>
                <p>Slimming down lanes will not only make drivers and pedestrians safer due to the tendency for drivers to go slower in areas they perceive as dangerous or narrow, but will also open up opportunities for multi-modal transportation. This means protected bike lanes or bus lanes, although the use of these modes of transport must first exist before seeing any use. These modes of transport should also be used as much as possible, as they are denser forms of transport and would ease traffic congestion. This fact is demonstrated by an Australian recreation of a world famous transport photograph, where the Cycling Promotion Fund writes that 69 volunteers demonstrated how you can fit each person on a bus, on bikes, and in 60 separate cars. In the space it took for 60 cars to fit across four lanes, it fit the same number of people plus nine more in a bus, in a quarter of a single lane (see Figure 1).</p>
                <figure className="essayfigure">
                    <a
                        href="/media/essays/lanes/CPF_TransportDensity.jpg"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <img
                            className="picture"
                            src="/media/essays/lanes/CPF_TransportDensity.jpg"
                            alt=""
                        />
                    </a>
                    <figcaption className="essaycaption">Figure 1: 69 volunteers demonstrate the dense nature of public transit. By getting people out of their cars and into a bus, you save fifteen-sixteenths (15/16) of four lanes spanning sixty cars. Original photographs uploaded by Stephen Hodge but originals are presumably lost online; copy acquired by Daniel Bowen via Flickr. No changes made.<br /><b>Click on the image for a detailed view in a new tab.</b></figcaption>
                </figure>
                <p>Streets should be narrowed to include lanes no more than nine feet wide. Narrow lanes on streets and roads will make the people outside cars, like pedestrians and bikers, safer from accidents. The narrow lanes would force drivers to pay closer attention to their surroundings and slow down, which would decrease the damage absorbed by a pedestrian if hit. Consumers and auto manufacturers should be regulated to lower the sale of SUVs and trucks, which would ease congestion and prevent numerous incidents involving pedestrians and cars alike. Streets should also include light fixtures and trees to force drivers to slow down further, thanks to their effect on width perception. The saved space after narrowing lanes could be used to implement public transit options like bike or bus lanes. These denser modes of transportation – alongside trains, subways, and walking – would save space in traffic for the people still using personal vehicles. This discussion of dense transportation and safety could expand on why we should use public transit, the health benefits of biking and walking, and how cities can be rebuilt to make biking or walking to locations less of a task.</p>
            </div>
            <WorksCited>
                <li><a href="https://web.archive.org/web/20120923195113/http://www.cyclingpromotion.com.au:80/content/view/566/9" target="_blank" rel="noopener noreferrer">“Australia Re-creates World Famous Transport Photo.” Cycling Promotion Fund, 18 Sept. 2012. Accessed 15 Mar. 2024.</a></li>
                <li><a href="https://nacto.org/wp-content/uploads/2015/04/narrow_residential_streets_daisa.pdf" target="_blank" rel="noopener noreferrer">Daisa, James, and John Peers. “Narrow Residential Streets: Do They Really Slow Down Speeds?” National Association of City Transportation Officials, 17 July 1997. Accessed 15 Mar. 2024.</a></li>
                <li><a href="http://www.strongtowns.org/journal/2024/3/7/the-stakes-in-the-suv-arms-race-go-way-beyond-safety" target="_blank" rel="noopener noreferrer">Durand-Wood, Emma. “The Stakes in the SUV ‘Arms Race’ Go Way Beyond Safety.” Strong Towns, 11 Mar. 2024. Accessed 15 Mar. 2024.</a></li>
                <li><a href="https://narrowlanes.americanhealth.jhu.edu/report/JHU-2023-Narrowing-Travel-Lanes-Report.pdf" target="_blank" rel="noopener noreferrer">Hamidi, Shima, et al. “A National Investigation on the Impacts of Lane Width on Traffic Safety: Narrowing Travel Lanes as an Opportunity to Promote Biking and Pedestrian Facilities Within the Existing Roadway Infrastructure.” Johns Hopkins Bloomberg School of Public Health, Nov. 2023. Accessed 15 Mar. 2024.</a></li>
                <li><a href="https://www.fhwa.dot.gov/publications/research/safety/pedbike/articles/walkable.htm" target="_blank" rel="noopener noreferrer">“Making America Walkable: It’s a Challenge We All Share.” United States Department of Transportation Federal Highway Administration. Accessed 15 Mar. 2024.</a></li>
                <li><a href="https://www.cdc.gov/transportationsafety/pedestrian_safety/index.html" target="_blank" rel="noopener noreferrer">“Pedestrian Safety.” Center for Disease Control and Prevention. Accessed 15 Mar. 2024.</a></li>
            </WorksCited>
        </>
    )
}